version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./model:/app/model
      - ./mlflow.db:/app/mlflow.db

  dashboard:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - api
    volumes:
      - ./model:/app/model
      - ./reports:/app/reports
      - ./mlflow.db:/app/mlflow.db

  mlflow:
    build: .
    ports:
      - "5000:5000"
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db
    volumes:
      - ./mlflow.db:/app/mlflow.db
    depends_on:
      - api